server:
  port: 8083

spring:
  application:
    name: attendance-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
      import-check:
        enabled: false
      retry:
        initial-interval: 1000
        max-attempts: 5
        multiplier: 1.5

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config:
      uri: http://config-server:8888
