#!/usr/bin/env bash
#
# fetch-verification-tokens.sh
# -----------------------------------------------------------------------------
# Extracts the email-verification tokens that auth-service stores in MySQL.
# This platform has no mailer, so the tokens are read straight from the auth
# database and fed into the Postman/Newman suite before the "Verify email"
# requests run.
#
# Usage (Newman / run-newman.sh flow):
#   fetch-verification-tokens.sh --from-export <vars.json> --out <env.json>
#
# Usage (manual Postman flow - emails in worker, employer, admin order):
#   fetch-verification-tokens.sh --emails worker.x@...,employer.x@...,admin.x@...
#   -> prints  workerVerifyToken=... / employerVerifyToken=... / adminVerifyToken=...
#      ready to paste into Postman collection variables.
#
# DB connection (defaults match docker-compose; override for local mvn runs):
#   DC_DB_HOST  (default localhost)
#   DC_DB_PORT  (default 3307     -> the docker host mapping; use 3306 for local)
#   DC_DB_USER  (default root)
#   DC_DB_PASS  (default root@123)
#   DC_AUTH_DB  (default auth_db  -> use domestic_connects_auth for local runs)
# -----------------------------------------------------------------------------
set -euo pipefail

DB_HOST="${DC_DB_HOST:-localhost}"
DB_PORT="${DC_DB_PORT:-3307}"
DB_USER="${DC_DB_USER:-root}"
DB_PASS="${DC_DB_PASS:-root@123}"
DB_NAME="${DC_AUTH_DB:-auth_db}"

FROM_EXPORT=""
EMAILS=""
OUT_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-export) FROM_EXPORT="$2"; shift 2 ;;
    --emails)      EMAILS="$2";      shift 2 ;;
    --out)         OUT_FILE="$2";    shift 2 ;;
    *) echo "ERROR: unknown argument '$1'" >&2; exit 2 ;;
  esac
done

# Resolve the emails from a Newman exported-variables file when requested.
if [[ -n "$FROM_EXPORT" ]]; then
  EMAILS="$(node -e '
    const fs = require("fs");
    const raw = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
    const vals = Array.isArray(raw.values)
      ? raw.values
      : Object.entries(raw).map(([k, v]) => ({ key: k, value: v }));
    const pick = (k) => { const e = vals.find(v => v.key === k); return e ? String(e.value) : ""; };
    const list = ["workerEmail", "employerEmail", "adminEmail"].map(pick).filter(Boolean);
    process.stdout.write(list.join(","));
  ' "$FROM_EXPORT")"
fi

if [[ -z "$EMAILS" ]]; then
  echo "ERROR: no emails available. Use --emails 'w@x,e@x,a@x' or --from-export <vars.json>." >&2
  exit 2
fi

if [[ -n "$OUT_FILE" && -z "$FROM_EXPORT" ]]; then
  echo "ERROR: --out requires --from-export (it merges the tokens into the exported vars)." >&2
  exit 2
fi

IFS=',' read -ra EMAIL_ARRAY <<< "$EMAILS"
if [[ ${#EMAIL_ARRAY[@]} -lt 1 || ${#EMAIL_ARRAY[@]} -gt 3 ]]; then
  echo "ERROR: expected 1-3 emails (worker, employer, admin), got ${#EMAIL_ARRAY[@]}." >&2
  exit 2
fi

# -----------------------------------------------------------------------------
# Query helper: local mysql client first, docker exec as fallback.
# -----------------------------------------------------------------------------
query_db() {
  local sql="$1"
  if command -v mysql >/dev/null 2>&1; then
    mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASS" -N -B -e "$sql" "$DB_NAME" 2>/dev/null || true
  else
    docker exec domestic-connects-mysql mysql -uroot -p"$DB_PASS" -N -B -e "$sql" "$DB_NAME" 2>/dev/null || true
  fi
}

TMP_TSV="$(mktemp)"
trap 'rm -f "$TMP_TSV"' EXIT

# -----------------------------------------------------------------------------
# Fetch one token per email (emails are generated by the suite, so plain
# single-quoting is sufficient).
# -----------------------------------------------------------------------------
for email in "${EMAIL_ARRAY[@]}"; do
  row="$(query_db "SELECT email, verification_token FROM users WHERE email = '$email';")"
  if [[ -z "$row" ]]; then
    echo "ERROR: no verification token for '$email' in DB '$DB_NAME'." >&2
    echo "       Did the account get registered? Is the right DB/port configured? (see header)" >&2
    exit 3
  fi
  token="${row#*$'\t'}"
  printf '%s\t%s\n' "$email" "$token" >> "$TMP_TSV"
done

if [[ -n "$OUT_FILE" ]]; then
  # Machine mode: merge the tokens into a Newman-compatible environment file.
  node -e '
    const fs = require("fs");
    const [tsvFile, fromExport, outFile] = process.argv.slice(1);
    const pairs = new Map(
      fs.readFileSync(tsvFile, "utf8").trim().split("\n").filter(Boolean)
        .map((l) => { const [e, t] = l.split("\t"); return [e, t]; })
    );
    let values = [];
    if (fromExport) {
      const raw = JSON.parse(fs.readFileSync(fromExport, "utf8"));
      values = Array.isArray(raw.values)
        ? raw.values.map((v) => ({ key: v.key, value: v.value, enabled: v.enabled !== false }))
        : Object.entries(raw).map(([k, v]) => ({ key: k, value: String(v), enabled: true }));
    }
    const map = { workerVerifyToken: "workerEmail", employerVerifyToken: "employerEmail", adminVerifyToken: "adminEmail" };
    for (const [tokenKey, emailKey] of Object.entries(map)) {
      const e = values.find((v) => v.key === emailKey);
      if (e && pairs.has(String(e.value))) {
        values = values.filter((v) => v.key !== tokenKey);
        values.push({ key: tokenKey, value: pairs.get(String(e.value)), enabled: true });
      }
    }
    fs.writeFileSync(outFile, JSON.stringify({
      id: "domestic-connects-it-env",
      name: "domestic-connects-it-env",
      values: values,
      _postman_variable_scope: "environment"
    }, null, 2));
    console.log("Wrote Newman environment with verification tokens: " + outFile);
  ' "$TMP_TSV" "$FROM_EXPORT" "$OUT_FILE"
else
  # Human mode: print the tokens for pasting into Postman collection variables.
  echo "workerVerifyToken=$(awk -F'\t' 'NR==1{print $2}' "$TMP_TSV")"
  if [[ ${#EMAIL_ARRAY[@]} -ge 2 ]]; then
    echo "employerVerifyToken=$(awk -F'\t' 'NR==2{print $2}' "$TMP_TSV")"
  fi
  if [[ ${#EMAIL_ARRAY[@]} -ge 3 ]]; then
    echo "adminVerifyToken=$(awk -F'\t' 'NR==3{print $2}' "$TMP_TSV")"
  fi
fi
